### 아이템 생성
POST localhost:8083/internal/common/item
Content-Type: application/json
Service-Code:eyJubyI6MSwidGl0bGUiOiJ0aXRsZSJ9

{
  "title": "fdghjkgfhjgfhjgfhjg",
  "description": "description",
  "thumbnail": "thumbnail"
}

### 아이템 조회
GET localhost:8083/internal/common/item?itemNo=1
Content-Type: application/json
Service-Code:eyJubyI6MSwidGl0bGUiOiJ0aXRsZSJ9

### 아이템 조회 (web)
GET localhost:8083/common/item?itemNo=1
Content-Type: application/json
Service-Code:eyJubyI6MSwidGl0bGUiOiJ0aXRsZSJ9
