### 아이템 생성
POST localhost:8084/internal/common/item
Content-Type: application/json
Service-Code:성

{
  "title": "fdghjkgfhjgfhjgfhjg",
  "description": "description",
  "thumbnail": "thumbnail"
}

### 아이템 조회
GET localhost:8084/internal/common/item?itemNo=1
Content-Type: application/json
Service-Code:eyJubyI6MSwidGl0bGUiOiJ0aXRsZSJ9

### 아이템 조회 (web)
GET localhost:8084/common/item?itemNo=1
Content-Type: application/json
Service-Code:eyJubyI6MSwidGl0bGUiOiJ0aXRsZSJ9

### 로그 정보 생성
POST localhost:8084/common/commonLog/info
Content-Type: application/json
Service-Code:eyJubyI6MSwidGl0bGUiOiJ0aXRsZSJ9

{
  "logName": "logName",
  "description": "description",
  "intColumn1Name": "intColumn1Name",
  "intColumn2Name": "intColumn2Name",
  "doubleColumn1Name": "doubleColumn1Name",
  "doubleColumn2Name": "doubleColumn2Name",
  "dateTimeColumn1Name": "dateTimeColumn1Name"
}

### 로그 정보 조회
GET localhost:8084/common/commonLog/info?commonLogInfoNo=1
Content-Type: application/json
Service-Code:eyJubyI6MSwidGl0bGUiOiJ0aXRsZSJ9