
spring:
  application:
    name: common
  cloud:
    config:
      enabled:false
    zookeeper:
      enabled: false
    openfeign:
      client:
        config:
          default:
            loggerLevel: basic
            connect-timeout: 4000
            read-timeout: 4000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/common-game?autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root
    cache-prep-stmts: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8083